### PR TITLE
Addition of help section

### PR DESCRIPTION
**Pull request by TomWFox**
I was somewhat unsure of the process of finding and editing the .bash_profile file so I found out and have added the process I went through:

I have added a section with terminal commands showing the process of finding/opening/editing the .bash_profile file.

Fixing typos.

### CODE REVIEW

**Comment by TomWFox** [comment]
I've merged your subsequent commits as well now, so there is no conflict.

**Review by agisilaos — APPROVED** [review]
LGTM. 👍

**Comment by TomWFox** [comment]
BTW - in my quest to become educated I looked up "LGTM" and came across two things:

1. It stands for "looks good to me"
2. A pull request security review service called [LGTM](https://lgtm.com)

I'm assuming 1 is the intended meaning but the second thing I found is quite a funny coincidence 🤣

**Comment by agisilaos** [comment]
Haha yep, it stands for "looks good to me". 👍

**Pull request merged**
